#!/usr/bin/env python
# -*- mode: Python; coding: latin-1 -*-
# Time-stamp: "2015-08-17 22:47:23 sb"

#  file       SConscript
#  copyright  (c) Sebastian Blatt 2013, 2014, 2015

# environment variables:
#   LIBPATH, LIBS, ASFLAGS, LINKFLAGS, CPPFLAGS, CPPPATH, CCFLAGS

Import('env')

env.StaticLibrary('sbutil',
                  ['CommandLine.cc',
                   'Const.cc',
                   'GSLMatrix.cc',
                   'HDF5File.cc',
                   'IPUtilities.cc',
                   'PerformanceCounter.cc',
                   'Point.cc',
                   'ProgressIndicator.cc',
                   'Random.cc',
                   'Representable.cc',
                   'Rotation.cc',
                   'SparseMatrixEvolver.cc',
                   'StringVector.cc',
                   'ThermalStatistics.cc',
                   'Tiff.cc',
                   'Timestamp.cc',
                   'UDPClient.cc',
                   'UDPPacket.cc',
                   'UDPServer.cc'
                   ])

# SConscript ends here
